login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
  path('', views.login_view, name='login'),

]

pc/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls', namespace='login')),
    path('index/', include('livro.urls', namespace='inicio')),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms




class LoginForm(forms.Form):
  username = forms.CharField(required=True)
  password = forms.CharField(required=True, widget=forms.PasswordInput)

login/views.py
from django.shortcuts import render
from login.forms import LoginForm
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect
from django.urls import reverse

# def login_view(request):
#
#     return render(request, 'login/login.html', {})



def login_view(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            # Redirect to a success page.
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('livro:index'))

            return render(request, 'login/login.html', {'form': form, 'mensage': 'Incorrect username or password.'})

    else:
        form = LoginForm()
    return  render(request, 'login/login.html', {'form': form})

login/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login de alguma coisa</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">


    <style rel="stylesheet">

        .imagemfundo {
            height: 110px;
            background-image: url({% static 'login/img/livro.jpg' %});
            background-size: 100% auto;
            background-repeat: no-repeat;

        }
        .corfundo{
            background-image: linear-gradient(to right, #b97c5d, #2a1a24);

        }


    </style>
</head>
<body class="login-page corfundo" >

<div class="container-fluid" id="wrapper">
    <div class="row">
        <main class="col-xs-10 col-sm-8 col-md-4 m-auto " style="max-width:500px;  border-radius: 54px;">
            <div class="login-panel card mt-5 shadow-lg mb-5  bg-white rounded" >
                <div class="imagemfundo">
                    <h3 class="card-title text-center mt-1 ">Login</h3>
                </div>
                <br>
                <div class="card-block ">

                    <div class="divider mt-0"></div>
                    <form role="form" action="{% url 'login:login' %}" method="post">
                        {% csrf_token %}
                        <div class="container ">
                            {% if form.username.value is not None %}
                                <span class="custom-control-description" style='color:red;font-size:14px;'> Usuário ou senha estão incorretos. </span>
                                {% endif %}

                            <div class="input-group input-group-lg">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-lg" style="width: 102px;">Usuario</span>
                                </div>
                                <input type="text" id="username" placeholder="Usuário" name="username"
                                       class="form-control" aria-label="Large"
                                       aria-describedby="inputGroup-sizing-sm" value="{% if form.username.value %} {{ form.username.value }} {% endif %}" type="text" required autofocus="">
                            </div>
                            <div class="input-group input-group-lg">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-lg"
                                          style="width: 102px;">Senha</span>
                                </div>
                                <input type="password" id="password" placeholder="Senha" name="password"
                                       class="form-control" aria-label="Large" required>
                            </div>

{#                            <div class="checkbox mt-1 mb-2">#}
{#                                <span class="custom-control-description"><a href="">Esqueceu sua senha?</a></span>#}
{#                            </div>#}
                            <div class="text-center mb-2">
                                <button type="submit" class="btn btn-lg btn-primary" style="width: 100%">Login</button>
                            </div>
{#                            <div class="text-center mb-2">#}
{#                                <a href="" class="btn btn-lg btn-secondary" style="width: 100%">Inscrever-se</a>#}
{#                            </div>#}
                        </div>
                    </form>
                </div>
            </div>
        </main>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

</body>
</html>