livro/urls.py
from django.urls import path
from . import views
from user.views import ListarUser
from django.contrib.auth import views as auth_views

app_name = 'livro'

urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  path('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),
  path('listar/', views.LivroList.as_view(), name='listar'),
  path('deletar/<int:pk>/', views.DeleteLivro.as_view(), name='delete'),
  path('editar/<int:pk>/', views.EditLivro.as_view(), name='editar'),
  path('pesquisar/', views.pesquisar, name='pesquisar'),
  path('listaruser/<codigo>/', ListarUser.as_view(), name='listUser'),
  path('emprestar/<livro>/', views.Emprestar.as_view(), name='emprestar'),
  path('aviso/<aviso>/', views.Aviso.as_view(), name='aviso'),
  path('devolver/<livro>/', views.Devolver.as_view(), name='devolver'),

]

pc/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls', namespace='login')),
    path('index/', include('livro.urls', namespace='inicio')),
]

livro/models.py
from django.db import models
from user.models import CustomUser

class Livro(models.Model):
    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    codigo = models.CharField(max_length=16)
    editora = models.CharField(max_length=200)
    emprestado = models.BooleanField("Emprestado?", blank=True, null=True,  default=False)
    user = models.ForeignKey(CustomUser, verbose_name='Usuário', blank=True, null=True, editable=True, on_delete=models.CASCADE)

    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        verbose_name = 'Livro'
        verbose_name_plural = 'Livros'
        ordering = ['titulo',]


    def __str__(self):
        return f"{self.titulo} - {self.autor} ({self.criado_em}/{self.atualizado_em})"

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser #User

# Create your models here.
class CustomUser(AbstractUser):
  is_admin = models.BooleanField('administrador', default=False)
  codigo = models.CharField(max_length=16)
  is_admin = models.BooleanField('administrador', default=False)
  email = models.EmailField(('email address'), unique=True,        error_messages={
            'unique': ("Email já existe."),
        },)
  REQUIRED_FIELDS = ['email', 'is_admin']
  username = models.CharField(
        ('username'),
        max_length=150,
        unique=True,
        help_text= ('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        error_messages={
            'unique': ("Usuario já existe."),
        },
    )
  class Meta:
    verbose_name = "Usuario"
    verbose_name_plural = "Usuarios"

  def __str__(self):
    return self.first_name if self.first_name is not None else self.username

livro/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm, PasswordChangeForm
from django.contrib.postgres.forms import RangeWidget # for DateRangeField
from .models import Livro



class LivroForm(forms.ModelForm):
    
    class Meta:
        model = Livro
        fields =  '__all__'
        widgets = {
            'titulo' : forms.TextInput(attrs={'class': 'form-control', 'required':''}),
            'autor' : forms.TextInput(attrs={'class': 'form-control', 'required':''}),
            'codigo' : forms.TextInput(attrs={'class': 'form-control', 'required':''}),
            'editora' : forms.TextInput(attrs={'class': 'form-control', 'required':''})

        }

livro/views.py
from django.shortcuts import render
from livro.models import  Livro
from livro.forms import LivroForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import  TemplateView
from django.views import View

from livro.models import Livro
from user.models import CustomUser

from django.shortcuts import render, get_object_or_404



# def index(request):
#
#     return render(request, 'livro/index.html', {})

def admin_check(user):
  return user.is_admin





@method_decorator(login_required, name='dispatch')
class Index(TemplateView):
    template_name = 'livro/index.html'

    # def dispatch(self, request, *args, **kwargs):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['livroemprestado'] = Livro.objects.filter(emprestado=True).count()
        context['livrodisponiveis'] = Livro.objects.filter(emprestado=False).count()
        context['usucomlivro'] = CustomUser.objects.filter(livro__emprestado=True).count()
        context['userativo'] = CustomUser.objects.filter(is_active=True).count()
        return context

@method_decorator(login_required,  name='dispatch')
class Cadastrar(CreateView):
    """
    View para a criação de novos livros.
    """
    model = Livro
    form_class = LivroForm
    template_name = 'livro/cadastrar.html'
    success_url = reverse_lazy('livro:listar')

@method_decorator(login_required, name='dispatch')
class LivroList(ListView):
    """
    View para listar veiculos livros.
    """
    model = Livro
    template_name = 'livro/listar.html'
    
@method_decorator(login_required, name='dispatch')
class DeleteLivro(DeleteView):
    """
    View para a exclusão de livro.
    """
    model = Livro
    template_name = 'livro/deletar.html'
    success_url = reverse_lazy('livro:listar')

@method_decorator(login_required, name='dispatch')
class EditLivro(UpdateView):
    """
    View para a edição de veiculos.
    """
    model = Livro
    form_class = LivroForm
    template_name = 'livro/editar.html'
    success_url = reverse_lazy('livro:listar')

@login_required
def pesquisar(request):
    if request.method == 'POST':
        return redirect("/index/listaruser/" + request.POST['codigo'] )
    return render(request, "livro/pesquisarUser.html", {})

@method_decorator(login_required, name='dispatch')
class Emprestar(TemplateView):
    template_name = 'livro/avisoOK.html'

    def post(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        livro = self.kwargs['livro']
        print(request.POST['codigo'] )
        print(self.kwargs['livro'] )
        user = get_object_or_404(CustomUser, codigo= request.POST['codigo'] )
        livro = get_object_or_404(Livro, id=livro)
        if  livro in user.livro_set.all() or livro.emprestado:
            return redirect('livro:aviso', "Livro Emprestado")
        livro.user = user
        livro.emprestado = True
        livro.save()
        return super().dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class Aviso(TemplateView):
    template_name = 'livro/aviso.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aviso'] = self.kwargs['aviso']
        return context

@method_decorator(login_required, name='dispatch')
class Devolver(View):

    def dispatch(self, request, *args, **kwargs):
        livro = self.kwargs['livro']
        livroObject = get_object_or_404(Livro, id=livro)
        livroObject.emprestado = False
        print(livroObject.user.id)
        livroObject.user_id = ""
        livroObject.save()
        return redirect('livro:aviso', "Livro Devolvido")
        return super().dispatch(request, *args, **kwargs)

user/views.py
from django.shortcuts import render
from livro.models import Livro
from user.models import CustomUser
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.views.generic import ListView

class ListarUser(ListView):
    model = CustomUser
    template_name = 'livro/user.html'

    def get_queryset(self, **kwargs):
        cod = self.kwargs['codigo']
        qs = get_object_or_404(self.model, codigo=cod)
        return qs

livro/templates/livro/aviso.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Editar Livro{%endblock%}

{% block container%}
    <div class="card-body">
        <h2>{{ aviso }}</h2>

    </div>
{%endblock%}

livro/templates/livro/avisoOK.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Editar Livro{%endblock%}

{% block container%}
    <div class="card-body">
        <h2>Emprestimo Efetuado</h2>


    </div>
{%endblock%}

livro/templates/livro/cadastrar.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Cadastrar Livro{%endblock%}

{% block container%}
<form action="{% url 'livro:cadastrar' %}" method="post">

    {% csrf_token %}
    <div class="card-body">

        <div class="col-md-6">
            <div class="form-group">
                {{ form.titulo.errors }}
                <label class="large mb-1" for="form.titulo.id_for_label">Titulo do Livro:</label>
                {{ form.titulo }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.autor.errors }}
                <label class="large mb-1" for="form.autor.id_for_label ">Autor do Livro:</label>
                {{ form.autor }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.codigo.errors }}
                <label class="large mb-1" for="form.codigo.id_for_label ">Código do Livro:</label>
                {{ form.codigo }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.editora.errors }}
                <label class="large mb-1" for="form.editora.id_for_label">Editora do Livro:</label>
                {{ form.editora }}
            </div>
        </div>


        <br>
        <a class="btn btn-danger" href="{% url 'livro:listar'%}"><i class="ti-close"></i> Cancelar</a>
        <button class="btn btn-success" type="submit"><i class="ti-save"></i> Salvar</button>
    </div>
</form>
{%endblock%}

livro/templates/livro/deletar.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Editar Livro{%endblock%}

{% block container%}
    <div class="card-body">

        		<form action="/index/deletar/{{ object.pk }}/" method="post">
			{% csrf_token %}
			<p>
				Tem certeza que deseja excluir o Livro "{{ object.titulo }}" de "{{object.autor}}" ?
			</p>
			<input class="btn-danger" type="submit" value="Confirmar" />
		</form>
    </div>
{%endblock%}

livro/templates/livro/editar.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Editar Livro{%endblock%}

{% block container%}
<form action="{% url 'livro:editar' object.pk %}" method="post">
    {% csrf_token %}
    <div class="card-body">

        <div class="col-md-6">
            <div class="form-group">
                {{ form.titulo.errors }}
                <label class="large mb-1" for="form.titulo.id_for_label">Titulo do Livro:</label>
                {{ form.titulo }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.autor.errors }}
                <label class="large mb-1" for="form.autor.id_for_label ">Autor do Livro:</label>
                {{ form.autor }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.codigo.errors }}
                <label class="large mb-1" for="form.codigo.id_for_label ">Código do Livro:</label>
                {{ form.codigo }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ form.editora.errors }}
                <label class="large mb-1" for="form.editora.id_for_label">Editora do Livro:</label>
                {{ form.editora }}
            </div>
        </div>


        <br>
        <a class="btn btn-danger" href="{% url 'livro:listar'%}"><i class="ti-close"></i> Cancelar</a>
        <button class="btn btn-success" type="submit"><i class="ti-save"></i> Salvar</button>
    </div>
</form>
{%endblock%}

livro/templates/livro/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block titulo %}Página Inicial{% endblock%}</title>
        <link href="{% static 'livro/dist/css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="/index">ReservaLivros <em><i class="fas fa-book"></i></em></a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
<!--                    <label class="" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />jhgh</div>-->

                    <div class="border">
                        <em class="btn btn-primary" type="button"><i class="fas fa-user"></i></em>
                    </div>
                    <h4 style="color: #ffffff">{{user.username}}</h4>
                </div>
            </form>
            <!-- Navbar-->
<!--            <ul class="navbar-nav ml-auto ml-md-0">-->
<!--                <li class="nav-item dropdown">-->
<!--                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>-->
<!--                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">-->
<!--                        <a class="dropdown-item" href="#">Settings</a>-->
<!--                        <a class="dropdown-item" href="#">Activity Log</a>-->
<!--                        <div class="dropdown-divider"></div>-->
<!--                        <a class="dropdown-item" href="login.html">Logout</a>-->
<!--                    </div>-->
<!--                </li>-->
<!--            </ul>-->
        </nav>
        <div id="layoutSidenav">

            <div id="layoutSidenav_nav">

                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">

                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Ações</div>
                            <a class="nav-link" href="{% url 'livro:listar' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Listar Livros
                            </a>
                            <a class="nav-link" href="{% url 'livro:cadastrar' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Cadastrar Livro
                            </a>
                            <a class="nav-link" href="{% url 'livro:pesquisar' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Pesquisar Usuario
                            </a>
<!--                            <div class="sb-sidenav-menu-heading">Interface</div>-->
<!--                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">-->
<!--                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>-->
<!--                                Layouts-->
<!--                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>-->
<!--                            </a>-->
<!--                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">-->
<!--                                <nav class="sb-sidenav-menu-nested nav">-->
<!--                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>-->
<!--                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>-->
<!--                                </nav>-->
<!--                            </div>-->
<!--                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">-->
<!--                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>-->
<!--                                Pages-->
<!--                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>-->
<!--                            </a>-->
<!--                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">-->
<!--                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">-->
<!--                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">-->
<!--                                        Authentication-->
<!--                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>-->
<!--                                    </a>-->
<!--                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">-->
<!--                                        <nav class="sb-sidenav-menu-nested nav">-->
<!--                                            <a class="nav-link" href="login.html">Login</a>-->
<!--                                            <a class="nav-link" href="register.html">Register</a>-->
<!--                                            <a class="nav-link" href="password.html">Forgot Password</a>-->
<!--                                        </nav>-->
<!--                                    </div>-->
<!--                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">-->
<!--                                        Error-->
<!--                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>-->
<!--                                    </a>-->
<!--                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">-->
<!--                                        <nav class="sb-sidenav-menu-nested nav">-->
<!--                                            <a class="nav-link" href="401.html">401 Page</a>-->
<!--                                            <a class="nav-link" href="404.html">404 Page</a>-->
<!--                                            <a class="nav-link" href="500.html">500 Page</a>-->
<!--                                        </nav>-->
<!--                                    </div>-->
<!--                                </nav>-->
<!--                            </div>-->
<!--                            <div class="sb-sidenav-menu-heading">Addons</div>-->
<!--                            <a class="nav-link" href="charts.html">-->
<!--                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>-->
<!--                                Charts-->
<!--                            </a>-->
<!--                            <a class="nav-link" href="tables.html">-->
<!--                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>-->
<!--                                Tables-->
<!--                            </a>-->
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
<!--                        <div class="small">Logged in as:</div>-->
<!--                        Start Bootstrap-->
                    </div>
                </nav>
            </div>

            <div id="layoutSidenav_content">

                <main>
                    <div class="container-fluid">
                        {% block container%}
                        <h1 class="mt-4">Dashboard Admin</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard Admin</li>
                        </ol>
                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">{{ livroemprestado }} livros emprestados</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#"></a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">{{ livrodisponiveis }} livros disponiveis</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#"></a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">{{ usucomlivro }} Usuarios com livros emprestados </div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#"></a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-info text-white mb-4">
                                    <div class="card-body">{{ userativo }} Usuarios ativos</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#"></a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        {%endblock%}
                    </div>
                </main>

                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Reservas De livros Online 2020</div>
                            <div>

                            </div>
                        </div>
                    </div>
                </footer>
            </div>


        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'livro/dist/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src=" {% static 'livro/dist/assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'livro/dist/assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'livro/dist/assets/demo/datatables-demo.js' %}"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

livro/templates/livro/pesquisarUser.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Usuario{%endblock%}

{% block container%}
{% csrf_token %}
<div class="card-body">
    <div class="card-body">
        <div class="table-responsive">

            <h4>Informe o codigo unico do usuario:</h4>
            <form action="{% url 'livro:pesquisar' %}" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control py-4" name="codigo" id="codigo" type="text" placeholder="Código"/>
                    </div>
                </div>

                        <button class="btn btn-success" type="submit"><i class="ti-save"></i> Pesquisar</button>



            </form>


        </div>
    </div>

</div>

{%endblock%}
{% block script%}
<script>
    $(document).ready(function () {
        // console.log($('#dataTable_previous'));
        $('#dataTable_previous').html("<a href='#' aria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"  class=\"page-link\"> Anterior </a>");
        $('#dataTable_next').html("<a href='#' aria-controls=\"dataTable\" data-dt-idx=\"2\" tabindex=\"2\"  class=\"page-link\"> Próximo </a>");
        //
        $('#dataTable_info').empty();
        $('.custom-select-sm').parent().empty();

    });
</script>
{%endblock%}

livro/templates/livro/user.html
{% extends 'livro/index.html'%}
{% load static %}
{% block titulo%}Usuario{%endblock%}

{% block container%}
{% csrf_token %}
<div class="card-body">
    <div class="card-body">
        <div class="table-responsive">
            <h4>Usuario <span style="color: #400101">{{object_list.username}} </span> tem os Seguites livres:</h4>

            <table class="table table-bordered" id="dataTabl" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Titulo</th>
                            <th>Autor</th>
                            <th>Código</th>
                            <th>Editora</th>
                            {% if user.is_superuser or user.is_admin %}
                            <th>Emprestado</th>
                            <th></th>
                            {% endif%}
                        </tr>
                        </thead>

                        <tbody>
                        {% for livro in object_list.livro_set.all %}
                        {% if livro.emprestado %}
                        <tr>
                            <td>{{livro.titulo}}</td>
                            <td>{{livro.autor}}</td>
                            <td>{{livro.codigo}}</td>
                            <td>{{livro.editora}}</td>
                            <td>{{livro.emprestado}}</td>
                            <td>
                                <a class="btn btn-light" href="/index/editar/{{ livro.pk }}/" value="Editar">Devolver</a>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor%}
                        </tbody>
                    </table>




        </div>
    </div>

</div>

{%endblock%}
{% block script%}
<script>
    $(document).ready(function () {
        // console.log($('#dataTable_previous'));
        $('#dataTable_previous').html("<a href='#' aria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"  class=\"page-link\"> Anterior </a>");
        $('#dataTable_next').html("<a href='#' aria-controls=\"dataTable\" data-dt-idx=\"2\" tabindex=\"2\"  class=\"page-link\"> Próximo </a>");
        //
        $('#dataTable_info').empty();
        $('.custom-select-sm').parent().empty();

    });
</script>
{%endblock%}